"""training runs

Revision ID: 235f1421da52
Revises: c18b5336f053
Create Date: 2026-09-09 09:06:08.321062+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '235f1421da52'
down_revision = 'c18b5336f053'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_run',
    sa.Column('panel_build_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage_detail', sa.String(length=300), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tiers', sa.String(length=120), nullable=False),
    sa.Column('min_history_profile', sa.String(length=30), nullable=False),
    sa.Column('xgboost_training_profile', sa.String(length=20), nullable=False),
    sa.Column('max_local_series', sa.Integer(), nullable=False),
    sa.Column('local_series_selection', sa.String(length=20), nullable=True),
    sa.Column('estimated_seconds', sa.Float(), nullable=True),
    sa.Column('estimate_json', sa.JSON(), nullable=True),
    sa.Column('total_budget_seconds', sa.Float(), nullable=True),
    sa.Column('per_model_timeout_seconds', sa.Float(), nullable=True),
    sa.Column('lstm_timeout_seconds', sa.Float(), nullable=True),
    sa.Column('series_requested', sa.Integer(), nullable=False),
    sa.Column('series_evaluated', sa.Integer(), nullable=False),
    sa.Column('model_runs_total', sa.Integer(), nullable=False),
    sa.Column('model_runs_completed', sa.Integer(), nullable=False),
    sa.Column('model_runs_ineligible', sa.Integer(), nullable=False),
    sa.Column('model_runs_failed', sa.Integer(), nullable=False),
    sa.Column('model_runs_timed_out', sa.Integer(), nullable=False),
    sa.Column('model_runs_not_evaluated', sa.Integer(), nullable=False),
    sa.Column('residuals_recorded', sa.Integer(), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('artifact_dir', sa.String(length=600), nullable=True),
    sa.Column('origins_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_build_id'], ['panel_build.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_run_panel_build_id'), ['panel_build_id'], unique=False)

    op.create_table('model_run',
    sa.Column('training_run_id', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('scope_level', sa.String(length=20), nullable=False),
    sa.Column('scope_key', sa.String(length=300), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=True),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evaluation_mode', sa.String(length=30), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('eligibility_json', sa.JSON(), nullable=True),
    sa.Column('seasonal_period', sa.Integer(), nullable=True),
    sa.Column('origins_completed', sa.Integer(), nullable=False),
    sa.Column('origins_total', sa.Integer(), nullable=False),
    sa.Column('validation_points', sa.Integer(), nullable=False),
    sa.Column('total_test_points', sa.Integer(), nullable=False),
    sa.Column('duplicate_test_points', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('wape', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('smape', sa.Float(), nullable=True),
    sa.Column('mase', sa.Float(), nullable=True),
    sa.Column('bias', sa.Float(), nullable=True),
    sa.Column('bias_abs', sa.Float(), nullable=True),
    sa.Column('naive_mae', sa.Float(), nullable=True),
    sa.Column('legacy_mape', sa.Float(), nullable=True),
    sa.Column('legacy_wape', sa.Float(), nullable=True),
    sa.Column('legacy_mae', sa.Float(), nullable=True),
    sa.Column('legacy_valid', sa.Boolean(), nullable=False),
    sa.Column('zero_actual_points', sa.Integer(), nullable=False),
    sa.Column('censored_points', sa.Integer(), nullable=False),
    sa.Column('negative_predictions', sa.Integer(), nullable=False),
    sa.Column('max_abs_prediction', sa.Float(), nullable=True),
    sa.Column('fit_seconds', sa.Float(), nullable=True),
    sa.Column('predict_seconds', sa.Float(), nullable=True),
    sa.Column('artifact_path', sa.String(length=600), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('origins_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_run_id', 'tier', 'scope_level', 'scope_key', 'model_id', name='uq_model_run_scope')
    )
    with op.batch_alter_table('model_run', schema=None) as batch_op:
        batch_op.create_index('ix_model_run_leaderboard', ['training_run_id', 'scope_level', 'wape'], unique=False)
        batch_op.create_index('ix_model_run_model', ['training_run_id', 'model_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_run_training_run_id'), ['training_run_id'], unique=False)

    op.create_table('quantile_calibration',
    sa.Column('training_run_id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('residual_count', sa.Integer(), nullable=False),
    sa.Column('offsets_json', sa.JSON(), nullable=False),
    sa.Column('pooling_level', sa.String(length=30), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_run_id', 'model_id', 'horizon', 'segment', name='uq_quantile_cell')
    )
    with op.batch_alter_table('quantile_calibration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantile_calibration_training_run_id'), ['training_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantile_calibration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quantile_calibration_training_run_id'))

    op.drop_table('quantile_calibration')
    with op.batch_alter_table('model_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_run_training_run_id'))
        batch_op.drop_index('ix_model_run_model')
        batch_op.drop_index('ix_model_run_leaderboard')

    op.drop_table('model_run')
    with op.batch_alter_table('training_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_run_panel_build_id'))

    op.drop_table('training_run')
    # ### end Alembic commands ###
