"""champion selections

Revision ID: 2b7edba9538f
Revises: 235f1421da52
Create Date: 2026-09-09 09:38:09.710784+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2b7edba9538f'
down_revision = '235f1421da52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion_selection',
    sa.Column('training_run_id', sa.String(length=32), nullable=False),
    sa.Column('scope_kind', sa.String(length=20), nullable=False),
    sa.Column('scope_key', sa.String(length=300), nullable=False),
    sa.Column('evaluated_scope_level', sa.String(length=20), nullable=True),
    sa.Column('champion_model_id', sa.String(length=40), nullable=False),
    sa.Column('champion_display_name', sa.String(length=80), nullable=False),
    sa.Column('challenger_model_id', sa.String(length=40), nullable=True),
    sa.Column('legacy_champion_model_id', sa.String(length=40), nullable=True),
    sa.Column('champion_model_run_id', sa.String(length=32), nullable=True),
    sa.Column('champion_wape', sa.Float(), nullable=True),
    sa.Column('champion_mae', sa.Float(), nullable=True),
    sa.Column('champion_bias', sa.Float(), nullable=True),
    sa.Column('champion_validation_points', sa.Integer(), nullable=False),
    sa.Column('champion_evaluation_mode', sa.String(length=30), nullable=True),
    sa.Column('best_baseline_model_id', sa.String(length=40), nullable=True),
    sa.Column('best_baseline_wape', sa.Float(), nullable=True),
    sa.Column('beaten_by_baseline', sa.Boolean(), nullable=False),
    sa.Column('selection_source', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.String(length=32), nullable=True),
    sa.Column('restored_from_id', sa.String(length=32), nullable=True),
    sa.Column('ranked_count', sa.Integer(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.Column('ranking_json', sa.JSON(), nullable=True),
    sa.Column('notes_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('champion_selection', schema=None) as batch_op:
        batch_op.create_index('ix_champion_active', ['is_active', 'scope_kind', 'scope_key'], unique=False)
        batch_op.create_index('ix_champion_run', ['training_run_id', 'scope_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_champion_selection_training_run_id'), ['training_run_id'], unique=False)
        batch_op.create_index('uq_champion_active_scope', ['scope_kind', 'scope_key'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('champion_selection', schema=None) as batch_op:
        batch_op.drop_index('uq_champion_active_scope', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active'))
        batch_op.drop_index(batch_op.f('ix_champion_selection_training_run_id'))
        batch_op.drop_index('ix_champion_run')
        batch_op.drop_index('ix_champion_active')

    op.drop_table('champion_selection')
    # ### end Alembic commands ###
