"""forecast runs and rows

Revision ID: 533752466943
Revises: 2b7edba9538f
Create Date: 2026-09-09 09:49:24.770424+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '533752466943'
down_revision = '2b7edba9538f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_run',
    sa.Column('training_run_id', sa.String(length=32), nullable=False),
    sa.Column('panel_build_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage_detail', sa.String(length=300), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('origin_period', sa.String(length=7), nullable=False),
    sa.Column('horizons', sa.String(length=40), nullable=False),
    sa.Column('requested_reconciliation', sa.String(length=30), nullable=True),
    sa.Column('reconciliation_method', sa.String(length=30), nullable=True),
    sa.Column('reconciliation_fallback_from', sa.String(length=30), nullable=True),
    sa.Column('reconciliation_fallback_reason', sa.Text(), nullable=True),
    sa.Column('shrinkage_intensity', sa.Float(), nullable=True),
    sa.Column('coherent', sa.Boolean(), nullable=False),
    sa.Column('max_incoherence', sa.Float(), nullable=True),
    sa.Column('negatives_clipped', sa.Integer(), nullable=False),
    sa.Column('quantile_crossings_corrected', sa.Integer(), nullable=False),
    sa.Column('series_forecast', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('rows_unavailable', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_build_id'], ['panel_build.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_run_panel_build_id'), ['panel_build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_run_training_run_id'), ['training_run_id'], unique=False)

    op.create_table('forecast_row',
    sa.Column('forecast_run_id', sa.String(length=32), nullable=False),
    sa.Column('scope_level', sa.String(length=20), nullable=False),
    sa.Column('scope_key', sa.String(length=300), nullable=False),
    sa.Column('canonical_branch', sa.String(length=120), nullable=True),
    sa.Column('canonical_sku', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('demand_segment', sa.String(length=20), nullable=True),
    sa.Column('value_class', sa.String(length=20), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=True),
    sa.Column('model_display_name', sa.String(length=80), nullable=True),
    sa.Column('model_run_id', sa.String(length=32), nullable=True),
    sa.Column('champion_selection_id', sa.String(length=32), nullable=True),
    sa.Column('forecast_source', sa.String(length=30), nullable=True),
    sa.Column('point_forecast', sa.Float(), nullable=True),
    sa.Column('q80', sa.Float(), nullable=True),
    sa.Column('q90', sa.Float(), nullable=True),
    sa.Column('q95', sa.Float(), nullable=True),
    sa.Column('base_forecast', sa.Float(), nullable=True),
    sa.Column('reconciliation_adjustment', sa.Float(), nullable=True),
    sa.Column('reconciliation_method', sa.String(length=30), nullable=True),
    sa.Column('quantile_method', sa.String(length=20), nullable=True),
    sa.Column('quantile_pooling_level', sa.String(length=30), nullable=True),
    sa.Column('quantile_residual_count', sa.Integer(), nullable=False),
    sa.Column('target_source', sa.String(length=20), nullable=True),
    sa.Column('is_censored', sa.Boolean(), nullable=True),
    sa.Column('unavailable_reason', sa.Text(), nullable=True),
    sa.Column('drivers_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_run_id', 'scope_level', 'scope_key', 'period', name='uq_forecast_scope_period')
    )
    with op.batch_alter_table('forecast_row', schema=None) as batch_op:
        batch_op.create_index('ix_forecast_lookup', ['forecast_run_id', 'scope_level', 'scope_key'], unique=False)
        batch_op.create_index('ix_forecast_period', ['forecast_run_id', 'period'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_row_forecast_run_id'), ['forecast_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_row', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_row_forecast_run_id'))
        batch_op.drop_index('ix_forecast_period')
        batch_op.drop_index('ix_forecast_lookup')

    op.drop_table('forecast_row')
    with op.batch_alter_table('forecast_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_run_training_run_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_run_panel_build_id'))

    op.drop_table('forecast_run')
    # ### end Alembic commands ###
