"""panel build

Revision ID: c18b5336f053
Revises: 195e0924d846
Create Date: 2026-09-09 07:31:19.945011+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c18b5336f053'
down_revision = '195e0924d846'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_build',
    sa.Column('preprocessing_run_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage_detail', sa.String(length=300), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('training_cut_period', sa.String(length=7), nullable=True),
    sa.Column('horizons', sa.String(length=40), nullable=False),
    sa.Column('panel_rows', sa.Integer(), nullable=False),
    sa.Column('series_count', sa.Integer(), nullable=False),
    sa.Column('period_count', sa.Integer(), nullable=False),
    sa.Column('observed_rows', sa.Integer(), nullable=False),
    sa.Column('materialised_zero_rows', sa.Integer(), nullable=False),
    sa.Column('censored_rows', sa.Integer(), nullable=False),
    sa.Column('training_rows', sa.Integer(), nullable=False),
    sa.Column('scoring_rows', sa.Integer(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('manifest_path', sa.String(length=600), nullable=True),
    sa.Column('artifacts_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preprocessing_run_id'], ['preprocessing_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('panel_build', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_build_preprocessing_run_id'), ['preprocessing_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panel_build', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_build_preprocessing_run_id'))

    op.drop_table('panel_build')
    # ### end Alembic commands ###
