"""Regenerate `data/scoped/` from the live panel build and the live settings.

`data/scoped/` is the committed, readable record of the slice this deployment
reports on. Nothing reads it at runtime, which is exactly why it rots: it
silently described the previous workspace for several SKU selections before
anyone noticed (docs/DECISIONS.md D-091). It was regenerated by hand each time,
and the hand-written manifest is where the drift crept in.

This does it from the two sources that cannot disagree with the application:
the panel artifact the app is currently serving, and the resolved workspace.

Run it after changing `AIS_WORKSPACE_BRANCHES` or `AIS_WORKSPACE_SKUS` and
rebuilding the panel:

    cd backend && ./.venv/bin/python ../scripts/export_scoped_slice.py

It writes `panel_scoped.parquet`, `product_dim_scoped.parquet` and
`manifest.json`, and prints what it wrote. It reads `data/source/` never.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.db.session import session_scope  # noqa: E402
from app.domain.ais.workspace import resolve_workspace  # noqa: E402
from app.models.mappings import PreprocessingRun  # noqa: E402
from app.models.panel import PanelBuild  # noqa: E402

OUT_DIR = REPO_ROOT / "data" / "scoped"

#: Carried through to the manifest so a reader can tell why these SKUs.
SELECTION_NOTE = (
    "The top 135 SKUs by combined BENGALURU + DELHI-1 invoiced value (AIS Basic "
    "Value, FY24-25 and FY25-26) among the 1,131 SKUs both branches sell - 80.1% "
    "of the two branches' combined revenue - plus FG.MP8.FDR.G00300A000, which "
    "ranks 177th but was one of the original twenty and is kept so the spread "
    "over vehicle category, glass type, value class and vehicle age chosen in "
    "D-075, D-081, D-082 and D-083 is not lost."
)


def _current_build(db):
    build = (
        db.query(PanelBuild)
        .filter(PanelBuild.status == "completed")
        .order_by(PanelBuild.created_at.desc())
        .first()
    )
    if build is None:
        raise SystemExit("No completed panel build. Build the panel first.")
    return build


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    with session_scope() as db:
        scope = resolve_workspace(db)
        build = _current_build(db)
        artifacts = dict(build.artifacts_json or {})
        summary = dict(build.summary_json or {})
        build_id = build.id
        grain = summary.get("grain") or "weekly"
        prep = db.get(PreprocessingRun, build.preprocessing_run_id)
        prep_artifacts = dict(prep.artifacts_json or {}) if prep else {}

    panel_path = artifacts.get("panel")
    if not panel_path or not Path(panel_path).exists():
        raise SystemExit(f"Panel artifact missing for build {build_id}.")

    panel = pd.read_parquet(panel_path)
    panel.to_parquet(OUT_DIR / "panel_scoped.parquet", index=False)

    branches = sorted(panel["canonical_branch"].unique().tolist())
    skus = sorted(panel["canonical_sku"].unique().tolist())
    periods = sorted(panel["period"].astype(str).unique().tolist())
    series = panel.groupby(["canonical_branch", "canonical_sku"]).ngroups

    # The product dimension, cut to the SKUs the panel actually contains -
    # not to the setting, so the export can never claim a SKU the panel lacks.
    product_rows = 0
    product_source = prep_artifacts.get("product_dim")
    if product_source and Path(product_source).exists():
        product_dim = pd.read_parquet(product_source)
        if "canonical_sku" in product_dim.columns:
            product_dim = product_dim[product_dim["canonical_sku"].isin(skus)]
        product_dim.to_parquet(OUT_DIR / "product_dim_scoped.parquet", index=False)
        product_rows = len(product_dim)

    total_branches = scope.total_branches
    total_skus = scope.total_skus
    manifest = {
        "purpose": (
            "The exact slice this deployment reports on. A derived export - the "
            "five client files in data/source/ are untouched and remain the "
            "system of record."
        ),
        "generated_by": "scripts/export_scoped_slice.py",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "panel_build_id": build_id,
        "branches": branches,
        "skus": skus,
        "series": series,
        "panel_rows": len(panel),
        "product_dim_rows": product_rows,
        "periods": [periods[0], periods[-1]] if periods else [],
        "period_count": len(periods),
        "grain": grain,
        "of_full_panel": {
            "branches": f"{len(branches)} of {total_branches}" if total_branches else str(len(branches)),
            "skus": f"{len(skus)} of {total_skus}" if total_skus else str(len(skus)),
        },
        "applied_by": (
            "AIS_WORKSPACE_BRANCHES and AIS_WORKSPACE_SKUS in backend/.env, via "
            "app/domain/ais/workspace.py, cut into the panel build by "
            "app/services/panel_service.py::_scope_artifacts"
        ),
        "sku_selection": SELECTION_NOTE,
        "workspace_source": scope.source,
        "workspace_detail": scope.detail,
    }
    (OUT_DIR / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )

    print(f"panel build      {build_id}")
    print(f"branches         {len(branches)}: {', '.join(branches)}")
    print(f"skus             {len(skus)}")
    print(f"series           {series}")
    print(f"panel rows       {len(panel):,}")
    print(f"periods          {len(periods)} ({periods[0]} -> {periods[-1]})" if periods else "")
    print(f"product_dim rows {product_rows}")
    print(f"written to       {OUT_DIR}")


if __name__ == "__main__":
    main()
